version: "3.8"
services:
  react-app:
    build:
      context: ../
      dockerfile: docker/dockerfile/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true